name: Tes Otomatis Pertama Gue
on: [push] # Instruksi: "Jalan setiap kali gue push kode"

jobs:
  job-ngetes-bash:
    runs-on: ubuntu-latest # Robotnya pakai server Ubuntu terbaru
    steps:
      - name: Ambil kode dari repo gue
        uses: actions/checkout@v4

      - name: Kasih izin eksekusi ke script
        run: chmod +x test.sh

      - name: Suruh robot jalanin scriptnya
        run: ./test.sh
